import type { Options } from './types.ts';

type LevelSpec = { id: string; name: string; chapter: string; lesson: string; options: Options };
const spec = (
  number: number,
  name: string,
  chapter: string,
  lesson: string,
  options: Partial<Options> = {},
): LevelSpec => ({
  id: `level-${number}`,
  name,
  chapter,
  lesson,
  options: {
    size: 9,
    regions: 'boxes',
    colors: false,
    diagonal: false,
    density: 'gentle',
    seed: `sudoku-garden-v1-${number}`,
    ...options,
  },
});

export const catalog: LevelSpec[] = [
  spec(
    1,
    'First light',
    '01 / The familiar',
    'Start with the classic: use 1–9 once in every row, column, and outlined 3×3 box. Pick an empty cell and look for its missing number.',
  ),
  spec(
    2,
    'Finding your rhythm',
    '01 / The familiar',
    'Look along a row, then down a column. Their clues work together. Pencil marks can hold your possibilities.',
  ),
  spec(
    3,
    'A pocket puzzle',
    '02 / A change of scale',
    'A smaller board, the same idea. This time you only need 1–4 in each row, column, and 2×2 box.',
    { size: 4 },
  ),
  spec(
    4,
    'Six of a kind',
    '02 / A change of scale',
    'Meet 1–6. Each outlined box is now 2 rows by 3 columns, with six cells to fill.',
    { size: 6 },
  ),
  spec(
    5,
    'Outside the box',
    '03 / New shapes',
    'Follow the thick outlines. Each jigsaw region has four connected cells and needs 1–4 once, just like a square box.',
    { size: 4, regions: 'jigsaw' },
  ),
  spec(
    6,
    'A little meander',
    '03 / New shapes',
    'Regions can turn corners. Select a cell to highlight the other cells in its outlined region.',
    { size: 6, regions: 'jigsaw' },
  ),
  spec(
    7,
    'Room to wander',
    '03 / New shapes',
    'Back to 1–9, with winding regions. Rows and columns still follow the familiar rules.',
    { regions: 'jigsaw' },
  ),
  spec(
    8,
    'A touch of color',
    '04 / Color connections',
    'A new connection: all rose A cells need 1–4 once, and all sage B cells do too. They can be far apart. Rows, columns, and boxes still count.',
    { size: 4, colors: true },
  ),
  spec(
    9,
    'Follow the color',
    '04 / Color connections',
    'Each color group now needs 1–6. The small A, B, and C labels match the colors, so you can follow either.',
    { size: 6, colors: true },
  ),
  spec(
    10,
    'A brighter picture',
    '04 / Color connections',
    'Three color groups, nine cells each. Every lettered color group contains 1–9 exactly once.',
    { colors: true },
  ),
  spec(
    11,
    'Crossing paths',
    '05 / A different angle',
    'The two dotted diagonals each need 1–4 once. All the usual row, column, and region rules remain.',
    { size: 4, diagonal: true },
  ),
  spec(
    12,
    'From corner to corner',
    '05 / A different angle',
    'Each dotted diagonal needs 1–9. The center cell belongs to both diagonals.',
    { diagonal: true },
  ),
  spec(
    13,
    'The bigger picture',
    '06 / More to discover',
    'A 12×12 board uses the numbers 1–12 in every row, column, and 3×4 box. Use the keypad, or A, B, and C for 10, 11, and 12.',
    { size: 12 },
  ),
  spec(
    14,
    'Colored contours',
    '07 / Better together',
    'Combine jigsaw regions and color groups. A cell can connect several different sets of clues.',
    { size: 6, regions: 'jigsaw', colors: true, density: 'balanced' },
  ),
  spec(
    15,
    'Winding diagonals',
    '07 / Better together',
    'Winding regions meet straight diagonals. Check both before placing a number.',
    { regions: 'jigsaw', diagonal: true, density: 'balanced' },
  ),
  spec(
    16,
    'Color at an angle',
    '07 / Better together',
    'Color groups and diagonals add two ways to narrow down your possibilities.',
    { colors: true, diagonal: true, density: 'balanced' },
  ),
  spec(
    17,
    'Everything in its place',
    '07 / Better together',
    'The whole collection of rules: jigsaw regions, color groups, and both diagonals. Take it one cell at a time.',
    { regions: 'jigsaw', colors: true, diagonal: true, density: 'balanced' },
  ),
  spec(
    18,
    'The grand garden',
    '07 / Better together',
    'All the rules on a 12×12 canvas, with fewer starting clues. Every row, column, outlined region, lettered color group, and dotted diagonal needs 1–12.',
    { size: 12, regions: 'jigsaw', colors: true, diagonal: true, density: 'sparse' },
  ),
];
